/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Upload } from "./Upload";
import { UploadCountArgs } from "./UploadCountArgs";
import { UploadFindManyArgs } from "./UploadFindManyArgs";
import { UploadFindUniqueArgs } from "./UploadFindUniqueArgs";
import { CreateUploadArgs } from "./CreateUploadArgs";
import { UpdateUploadArgs } from "./UpdateUploadArgs";
import { DeleteUploadArgs } from "./DeleteUploadArgs";
import { Document } from "../../document/base/Document";
import { UploadService } from "../upload.service";
@graphql.Resolver(() => Upload)
export class UploadResolverBase {
  constructor(protected readonly service: UploadService) {}

  async _uploadsMeta(
    @graphql.Args() args: UploadCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Upload])
  async uploads(@graphql.Args() args: UploadFindManyArgs): Promise<Upload[]> {
    return this.service.uploads(args);
  }

  @graphql.Query(() => Upload, { nullable: true })
  async upload(
    @graphql.Args() args: UploadFindUniqueArgs
  ): Promise<Upload | null> {
    const result = await this.service.upload(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Upload)
  async createUpload(@graphql.Args() args: CreateUploadArgs): Promise<Upload> {
    return await this.service.createUpload({
      ...args,
      data: {
        ...args.data,

        document: args.data.document
          ? {
              connect: args.data.document,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Upload)
  async updateUpload(
    @graphql.Args() args: UpdateUploadArgs
  ): Promise<Upload | null> {
    try {
      return await this.service.updateUpload({
        ...args,
        data: {
          ...args.data,

          document: args.data.document
            ? {
                connect: args.data.document,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Upload)
  async deleteUpload(
    @graphql.Args() args: DeleteUploadArgs
  ): Promise<Upload | null> {
    try {
      return await this.service.deleteUpload(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Document, {
    nullable: true,
    name: "document",
  })
  async getDocument(
    @graphql.Parent() parent: Upload
  ): Promise<Document | null> {
    const result = await this.service.getDocument(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
