/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UploadService } from "../upload.service";
import { UploadCreateInput } from "./UploadCreateInput";
import { Upload } from "./Upload";
import { UploadFindManyArgs } from "./UploadFindManyArgs";
import { UploadWhereUniqueInput } from "./UploadWhereUniqueInput";
import { UploadUpdateInput } from "./UploadUpdateInput";

export class UploadControllerBase {
  constructor(protected readonly service: UploadService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Upload })
  async createUpload(@common.Body() data: UploadCreateInput): Promise<Upload> {
    return await this.service.createUpload({
      data: {
        ...data,

        document: data.document
          ? {
              connect: data.document,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        document: {
          select: {
            id: true,
          },
        },

        fileName: true,
        filePath: true,
        fileSize: true,
        fileType: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Upload] })
  @ApiNestedQuery(UploadFindManyArgs)
  async uploads(@common.Req() request: Request): Promise<Upload[]> {
    const args = plainToClass(UploadFindManyArgs, request.query);
    return this.service.uploads({
      ...args,
      select: {
        createdAt: true,

        document: {
          select: {
            id: true,
          },
        },

        fileName: true,
        filePath: true,
        fileSize: true,
        fileType: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Upload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async upload(
    @common.Param() params: UploadWhereUniqueInput
  ): Promise<Upload | null> {
    const result = await this.service.upload({
      where: params,
      select: {
        createdAt: true,

        document: {
          select: {
            id: true,
          },
        },

        fileName: true,
        filePath: true,
        fileSize: true,
        fileType: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Upload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUpload(
    @common.Param() params: UploadWhereUniqueInput,
    @common.Body() data: UploadUpdateInput
  ): Promise<Upload | null> {
    try {
      return await this.service.updateUpload({
        where: params,
        data: {
          ...data,

          document: data.document
            ? {
                connect: data.document,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          document: {
            select: {
              id: true,
            },
          },

          fileName: true,
          filePath: true,
          fileSize: true,
          fileType: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Upload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUpload(
    @common.Param() params: UploadWhereUniqueInput
  ): Promise<Upload | null> {
    try {
      return await this.service.deleteUpload({
        where: params,
        select: {
          createdAt: true,

          document: {
            select: {
              id: true,
            },
          },

          fileName: true,
          filePath: true,
          fileSize: true,
          fileType: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
