/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccessControlUpdateManyWithoutDocumentsInput } from "./AccessControlUpdateManyWithoutDocumentsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { BlockchainRecordUpdateManyWithoutDocumentsInput } from "./BlockchainRecordUpdateManyWithoutDocumentsInput";
import { UploadUpdateManyWithoutDocumentsInput } from "./UploadUpdateManyWithoutDocumentsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class DocumentUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AccessControlUpdateManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => AccessControlUpdateManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => AccessControlUpdateManyWithoutDocumentsInput, {
    nullable: true,
  })
  accessControls?: AccessControlUpdateManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: () => BlockchainRecordUpdateManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => BlockchainRecordUpdateManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => BlockchainRecordUpdateManyWithoutDocumentsInput, {
    nullable: true,
  })
  blockchainRecords?: BlockchainRecordUpdateManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  hash?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => UploadUpdateManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => UploadUpdateManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => UploadUpdateManyWithoutDocumentsInput, {
    nullable: true,
  })
  uploads?: UploadUpdateManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { DocumentUpdateInput as DocumentUpdateInput };
