/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Document as PrismaDocument,
  AccessControl as PrismaAccessControl,
  BlockchainRecord as PrismaBlockchainRecord,
  Upload as PrismaUpload,
  User as PrismaUser,
} from "@prisma/client";

export class DocumentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.DocumentCountArgs, "select">): Promise<number> {
    return this.prisma.document.count(args);
  }

  async documents(
    args: Prisma.DocumentFindManyArgs
  ): Promise<PrismaDocument[]> {
    return this.prisma.document.findMany(args);
  }
  async document(
    args: Prisma.DocumentFindUniqueArgs
  ): Promise<PrismaDocument | null> {
    return this.prisma.document.findUnique(args);
  }
  async createDocument(
    args: Prisma.DocumentCreateArgs
  ): Promise<PrismaDocument> {
    return this.prisma.document.create(args);
  }
  async updateDocument(
    args: Prisma.DocumentUpdateArgs
  ): Promise<PrismaDocument> {
    return this.prisma.document.update(args);
  }
  async deleteDocument(
    args: Prisma.DocumentDeleteArgs
  ): Promise<PrismaDocument> {
    return this.prisma.document.delete(args);
  }

  async findAccessControls(
    parentId: string,
    args: Prisma.AccessControlFindManyArgs
  ): Promise<PrismaAccessControl[]> {
    return this.prisma.document
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .accessControls(args);
  }

  async findBlockchainRecords(
    parentId: string,
    args: Prisma.BlockchainRecordFindManyArgs
  ): Promise<PrismaBlockchainRecord[]> {
    return this.prisma.document
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .blockchainRecords(args);
  }

  async findUploads(
    parentId: string,
    args: Prisma.UploadFindManyArgs
  ): Promise<PrismaUpload[]> {
    return this.prisma.document
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .uploads(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.document
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
