/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccessControl } from "../../accessControl/base/AccessControl";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { BlockchainRecord } from "../../blockchainRecord/base/BlockchainRecord";
import { Upload } from "../../upload/base/Upload";
import { User } from "../../user/base/User";

@ObjectType()
class Document {
  @ApiProperty({
    required: false,
    type: () => [AccessControl],
  })
  @ValidateNested()
  @Type(() => AccessControl)
  @IsOptional()
  accessControls?: Array<AccessControl>;

  @ApiProperty({
    required: false,
    type: () => [BlockchainRecord],
  })
  @ValidateNested()
  @Type(() => BlockchainRecord)
  @IsOptional()
  blockchainRecords?: Array<BlockchainRecord>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  hash!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Upload],
  })
  @ValidateNested()
  @Type(() => Upload)
  @IsOptional()
  uploads?: Array<Upload>;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  user?: User | null;
}

export { Document as Document };
