/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccessControlCreateNestedManyWithoutDocumentsInput } from "./AccessControlCreateNestedManyWithoutDocumentsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { BlockchainRecordCreateNestedManyWithoutDocumentsInput } from "./BlockchainRecordCreateNestedManyWithoutDocumentsInput";
import { UploadCreateNestedManyWithoutDocumentsInput } from "./UploadCreateNestedManyWithoutDocumentsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class DocumentCreateInput {
  @ApiProperty({
    required: false,
    type: () => AccessControlCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => AccessControlCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => AccessControlCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  accessControls?: AccessControlCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: () => BlockchainRecordCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => BlockchainRecordCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => BlockchainRecordCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  blockchainRecords?: BlockchainRecordCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  hash?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => UploadCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => UploadCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => UploadCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  uploads?: UploadCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { DocumentCreateInput as DocumentCreateInput };
